[package]
name = "downloader-cli"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
app-actions.workspace = true
app-config.workspace = true
clap.workspace = true
futures.workspace = true
http = "1.4.2"
serde.workspace = true
tikv-jemallocator.workspace = true
tokio.workspace = true
tracing.workspace = true
tracing-subscriber.workspace = true
url.workspace = true
validator.workspace = true

[lints]
workspace = true
