[package]
name = "app-requests"
version.workspace = true
edition.workspace = true
description.workspace = true
license.workspace = true

[dependencies]
derive_more.workspace = true
http = "1.4.2"
http-serde = "2.1.1"
reqwest = { version = "0.13.4", default-features = false, features = ["brotli", "cookies", "deflate", "gzip", "json", "multipart", "rustls", "stream"] }
rustls = { version = "0.23", default-features = false, features = ["aws_lc_rs", "logging", "std", "tls12"] }
rustls-native-certs = "0.8"
serde.workspace = true
url.workspace = true
webpki-root-certs = "1.0.7"

[lints]
workspace = true
